### ISSUE TITLE
A little help

### ISSUE THREAD

**Issue by pachof** [ChefKissInc/LegacyRed#18]
### macOS Version

Big Sur

### What is your CPU's model?

AMD E1-6010

### Please describe the feature in detail.

Hello, I am looking for an efi for my hp 19-2205la computer, with amd e1-6010 and radeon r2, I am asking here because it is possible that in this repository there is one that has the efi so that I can install mac os, if anyone has and it is very compatible with my pc, please pass it on to me and I will be deeply grateful. My pc have 8GB of ram, In addition to hopefully adding compatibility with High Sierra

### What alternatives have you tried, if any?

I have had no alternatives

### Feature request submission terms

- [X] I am using the latest version of LegacyRed, thereby extension the feature is not already present.
- [X] I am on the latest minor and patch version of macOS (ex. 7 is the minor and 10 is the patch of macOS 11.7.10).
- [X] The feature being present in LegacyRed makes sense.
- [X] I have ruled out any external factors that could interfere, including, but not limited to, using OCLP or WhateverGreen.

**Comment by Zormeister** [comment]
We do not support anyone who uses a prebuilt EFI folder.
Use the Dortania guide (ignoring the AMD Laptop discouragement) alongside the recommendations from the README.

High Sierra support is not a work in progress at this tine and is not a guaranteed feature.
